[package]
name = "tangerine"
version = "0.0.1"
authors = ["Andrew Zitek <alz236@nyu.edu>"]
edition = "2018"
[dependencies]
crypto-hash = "0.3.4"
num-bigint = { version = "0.4", features = ["rand"] }
num-integer = "0.1.44"
num-traits = "0.2.14"
rand = "0.8"
